version: "3.8"
name: side-by-side

volumes:
  app_data:
  app_state:
  app_logs:
  pgdata:

services:
  server:
    image: ${IMAGE_REGISTRY:-ghcr.io/mikeozornin}/side-by-side-server:${IMAGE_TAG:-latest}
    # build: ../../server  # Uncomment for local build
    env_file: .env
    environment:
      - PORT=3000
      - NODE_ENV=production
      - STORAGE_DRIVER=${STORAGE_DRIVER:-local}
      - DATA_DIR=/var/app/data
      - LOG_DIR=/var/app/logs
      - DB_PROVIDER=${DB_PROVIDER:-sqlite}
      - DB_PATH=/var/app/state/app.db
      - BASE_URL=${BASE_URL:-http://localhost}
      - CLIENT_URL=${CLIENT_URL:-http://localhost}
      - JWT_SECRET=${JWT_SECRET}
      - AUTH_MODE=${AUTH_MODE:-magic-links}
      - AUTO_APPROVE_SESSIONS=${AUTO_APPROVE_SESSIONS:-false}
      # SMTP settings (optional)
      - SMTP_HOST=${SMTP_HOST:-}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER:-}
      - SMTP_PASS=${SMTP_PASS:-}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL:-noreply@side-by-side.com}
      # Web Push settings (optional)
      - WEB_PUSH_ENABLED=${WEB_PUSH_ENABLED:-false}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY:-}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY:-}
      - VAPID_EMAIL=${VAPID_EMAIL:-mailto:admin@side-by-side.com}
      # S3 settings (optional)
      - S3_ENDPOINT=${S3_ENDPOINT:-}
      - S3_REGION=${S3_REGION:-us-east-1}
      - S3_BUCKET=${S3_BUCKET:-}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID:-}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY:-}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE:-true}
      # PostgreSQL settings (if using postgres)
      - DATABASE_URL=${DATABASE_URL:-}
    volumes:
      - app_data:/var/app/data
      - app_state:/var/app/state
      - app_logs:/var/app/logs
    expose: ["3000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  client:
    image: ${IMAGE_REGISTRY:-ghcr.io/mikeozornin}/side-by-side-client:${IMAGE_TAG:-latest}
    # build: ../../client  # Uncomment for local build
    environment:
      - VITE_API_URL=${VITE_API_URL:-/api}
      - VITE_CLIENT_URL=${VITE_CLIENT_URL:-http://localhost}
    restart: unless-stopped

  edge:
    image: nginx:alpine
    ports: ["80:80"]
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      client:
        condition: service_started
      server:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-sidebyside}
      - POSTGRES_USER=${POSTGRES_USER:-sideuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-sidepass}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-sideuser} -d ${POSTGRES_DB:-sidebyside}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    profiles: ["postgres"]

