---
- name: Deploy Side-by-Side Voting release

  hosts: web
  become: true
  vars:
    release_ts: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"
    release_path: "{{ release_root }}/{{ release_ts }}"
  tasks:
    - name: Freeze release timestamp once per run
      set_fact:
        release_ts: "{{ release_ts | default(lookup('pipe', 'date +%Y%m%d_%H%M%S')) }}"
        release_path: "{{ release_root }}/{{ release_ts }}"
      run_once: true

    - name: Optionally update env file on server from local source
      when: update_env | bool
      copy:
        src: "{{ local_env_src }}"
        dest: "{{ env_file_path }}"
        owner: root
        group: www-data
        mode: "0640"
      no_log: true

    - name: Update AUTH_MODE in env file if specified
      when: auth_mode is defined
      lineinfile:
        path: "{{ env_file_path }}"
        regexp: '^AUTH_MODE='
        line: "AUTH_MODE={{ auth_mode }}"
        owner: root
        group: www-data
        mode: "0640"

    - name: Create release directories
      file:
        path: "{{ item }}"
        state: directory
        owner: www-data
        group: www-data
        mode: "0755"
      loop:
        - "{{ release_path }}"
        - "{{ release_path }}/frontend"
        - "{{ release_path }}/server"
        - "{{ release_path }}/data"
        - "{{ release_path }}/logs"

    - name: Sync frontend artifacts
      synchronize:
        src: "{{ playbook_dir }}/../client/dist/"
        dest: "{{ release_path }}/frontend/"
        delete: yes

    - name: Sync backend artifacts (dist + package files)
      synchronize:
        src: "{{ playbook_dir }}/../server/"
        dest: "{{ release_path }}/server/"
        delete: yes
        rsync_path: "rsync"
        rsync_opts:
          - "--exclude=app.db"
          - "--exclude=*.db"
          - "--exclude=*.sqlite"
          - "--exclude=*.sqlite3"
          - "--exclude=data/"
          - "--exclude=logs/"
          - "--exclude=.env*"

    - name: Remove unnecessary backend files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ release_path }}/server/node_modules"
        - "{{ release_path }}/server/src"
        - "{{ release_path }}/server/.git"
        - "{{ release_path }}/server/.github"
        - "{{ release_path }}/server/tsconfig.json"
        - "{{ release_path }}/server/jest.config.js"
        - "{{ release_path }}/server/README.md"
        - "{{ release_path }}/server/NOTIFICATIONS.md"
        - "{{ release_path }}/server/package-lock.json"
        - "{{ release_path }}/server/yarn.lock"
        - "{{ release_path }}/server/pnpm-lock.yaml"
        - "{{ release_path }}/server/bun.lock"

    - name: Ensure backend contains only dist and package files
      shell: |
        shopt -s extglob || true
        cd "{{ release_path }}/server" && {
          find . -maxdepth 1 -type f ! -name 'package.json' ! -name 'bun.lock' ! -path './dist/*' -delete || true;
        }
      args:
        executable: /bin/bash

    - name: Copy data directory from current if exists
      shell: |
        if [ -d "{{ current_link }}/data" ] && [ "$(ls -A {{ current_link }}/data)" ]; then
          cp -r {{ current_link }}/data/* {{ release_path }}/data/ 2>/dev/null || true
        fi
      args:
        executable: /bin/bash

    - name: Copy database from current if exists
      shell: |
        if [ -f "{{ current_link }}/app.db" ]; then
          cp {{ current_link }}/app.db {{ release_path }}/app.db
          chown www-data:www-data {{ release_path }}/app.db
          chmod 644 {{ release_path }}/app.db
        fi
      args:
        executable: /bin/bash
      when: db_provider == 'sqlite'

    - name: Copy logs directory from current if exists
      shell: |
        if [ -d "{{ current_link }}/logs" ] && [ "$(ls -A {{ current_link }}/logs)" ]; then
          cp -r {{ current_link }}/logs/* {{ release_path }}/logs/ 2>/dev/null || true
        fi
      args:
        executable: /bin/bash

    - name: Ensure release ownership (recursive)
      file:
        path: "{{ release_path }}"
        owner: www-data
        group: www-data
        recurse: true

    - name: Install production deps on server with Bun
      shell: |
        set -e
        cd "{{ release_path }}/server"
        # Remove old lockfiles to avoid conflicts
        rm -f package-lock.json yarn.lock pnpm-lock.yaml
        # Install with Bun (it will create bun.lock)
        bun install --production
      args:
        executable: /bin/bash

    - name: Write manifest
      copy:
        dest: "{{ release_path }}/manifest.json"
        content: |
          {"deployed_at": "{{ release_ts }}", "domain": "{{ domain }}", "version": "{{ ansible_date_time.iso8601 }}"}
        owner: www-data
        group: www-data
        mode: "0644"

    - name: Switch current symlink
      file:
        src: "{{ release_path }}"
        dest: "{{ current_link }}"
        state: link
        force: true

    - name: Ensure nginx web root links to current/frontend
      file:
        src: "{{ current_link }}/frontend"
        dest: "{{ nginx_web_root }}"
        state: link
        force: true

    - name: Restart service (optional)
      when: restart_service | bool
      systemd:
        name: "{{ service_name }}"
        state: restarted

    - name: Prune old releases, keep last N
      shell: |
        set -e
        ls -1dt "{{ release_root }}"/* | tail -n +$(( {{ releases_to_keep }} + 1 )) | xargs -r rm -rf
      args:
        executable: /bin/bash

    - name: Health check
      uri:
        url: "https://{{ domain }}{{ health_path }}"
        method: GET
        status_code: 200
        validate_certs: yes
      ignore_errors: yes

    - name: Display deployment info
      debug:
        msg: |
          Deployment completed!
          Release: {{ release_ts }}
          Path: {{ release_path }}
          Domain: {{ domain }}
          Health check: https://{{ domain }}{{ health_path }}
